#index:
#    path: /
#    controller: App\Controller\DefaultController::index
juicio:
    path: /
    controller: App\Controller\JuicioController::index
addUser:
    path: /createUser/{name}/{dni}/{tipo}
    controller: App\Controller\JuicioController::createUser
    methods:    GET|POST
