juicio:
    path: /
    controller: App\Controller\JuicioController::index
addUser:
    path: /createUser/{name}/{dni}/{tipo}
    controller: App\Controller\JuicioController::createUser
    methods:    GET|POST
checkVs:
    path: /checkVs/{a1}/{b1}/{c1}/{ab1}/{bb1}/{cb1}/{nombre1}/{nombre2}
    controller: App\Controller\JuicioController::checkVs
    methods:    GET|POST
